
package one.microstream.jcon22_productappjpa.ui;

import com.flowingcode.vaadin.addons.ironicons.IronIcons;
import com.rapidclipse.framework.server.data.converter.ConverterBuilder;
import com.rapidclipse.framework.server.resources.CaptionUtils;
import com.rapidclipse.framework.server.ui.ItemLabelGeneratorFactory;
import com.rapidclipse.framework.server.ui.StartsWithIgnoreCaseItemFilter;
import com.rapidclipse.framework.server.ui.UIUtils;
import com.vaadin.flow.component.ClickEvent;
import com.vaadin.flow.component.ComponentEvent;
import com.vaadin.flow.component.ComponentEventListener;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.checkbox.Checkbox;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.dialog.Dialog;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.formlayout.FormLayout.FormItem;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.BigDecimalField;
import com.vaadin.flow.component.textfield.NumberField;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.data.binder.Binder;
import com.vaadin.flow.data.binder.ValidationException;
import com.vaadin.flow.data.provider.DataProvider;
import com.vaadin.flow.function.SerializableRunnable;

import one.microstream.jcon22_productappjpa.dal.CategoryDAO;
import one.microstream.jcon22_productappjpa.dal.ProductDAO;
import one.microstream.jcon22_productappjpa.dal.SupplierDAO;
import one.microstream.jcon22_productappjpa.domain.Category;
import one.microstream.jcon22_productappjpa.domain.Product;
import one.microstream.jcon22_productappjpa.domain.Supplier;


public class PopupProduct extends VerticalLayout
{

	private final Product              product;
	private final SerializableRunnable onOK;
	
	/**
	 *
	 */
	public PopupProduct(final Product product, final SerializableRunnable onOK)
	{
		super();
		this.product = product;
		this.onOK    = onOK;
		this.initUI();

		this.binder.readBean(product);
		
		this.binder.validate();
	}
	
	/**
	 * Event handler delegate method for the {@link Button} {@link #btnCancel}.
	 *
	 * @see ComponentEventListener#onComponentEvent(ComponentEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void btnCancel_onClick(final ClickEvent<Button> event)
	{
		UIUtils.getNextParent(this, Dialog.class).close();
	}

	/**
	 * Event handler delegate method for the {@link Button} {@link #btnOK}.
	 *
	 * @see ComponentEventListener#onComponentEvent(ComponentEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void btnOK_onClick(final ClickEvent<Button> event)
	{
		
		if(this.binder.isValid())
		{
			try
			{
				this.binder.writeBean(this.product);
				new ProductDAO().save(this.product);
				this.onOK.run();
				UIUtils.getNextParent(this, Dialog.class).close();
			}
			catch(final ValidationException e)
			{
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}
	
	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.form               = new FormLayout();
		this.formItem           = new FormItem();
		this.lblProductname     = new Label();
		this.txtProductname     = new TextField();
		this.formItem2          = new FormItem();
		this.lblCategory        = new Label();
		this.cmbCategory        = new ComboBox<>();
		this.formItem3          = new FormItem();
		this.lblSupplier        = new Label();
		this.cmbSupplier        = new ComboBox<>();
		this.formItem4          = new FormItem();
		this.lblDiscontinued    = new Label();
		this.chkDiscontinued    = new Checkbox();
		this.formItem5          = new FormItem();
		this.lblUnitprice       = new Label();
		this.bigdUnitprice      = new BigDecimalField();
		this.formItem6          = new FormItem();
		this.lblUnitsinstock    = new Label();
		this.nrUnitsinstock     = new NumberField();
		this.formItem7          = new FormItem();
		this.lblQuantityperunit = new Label();
		this.txtQuantityperunit = new TextField();
		this.formItem8          = new FormItem();
		this.lblUnitsonorder    = new Label();
		this.nrUnitsonorder     = new NumberField();
		this.binder             = new Binder<>();
		this.horizontalLayout   = new HorizontalLayout();
		this.btnCancel          = new Button();
		this.btnOK              = new Button();

		this.setPadding(false);
		this.form.setResponsiveSteps(
			new FormLayout.ResponsiveStep("0px", 1, FormLayout.ResponsiveStep.LabelsPosition.TOP),
			new FormLayout.ResponsiveStep("500px", 2, FormLayout.ResponsiveStep.LabelsPosition.TOP));
		this.formItem.getElement().setAttribute("colspan", "2");
		this.lblProductname.setText("Productname");
		this.txtProductname.setTabIndex(1);
		this.lblCategory.setText("Category");
		this.cmbCategory.setTabIndex(2);
		this.cmbCategory.setDataProvider(StartsWithIgnoreCaseItemFilter.New(this.cmbCategory::getItemLabelGenerator),
			DataProvider.ofCollection(CategoryDAO.INSTANCE.findAll()));
		this.cmbCategory.setItemLabelGenerator(ItemLabelGeneratorFactory.NonNull(CaptionUtils::resolveCaption));
		this.lblSupplier.setText("Supplier");
		this.cmbSupplier.setTabIndex(3);
		this.cmbSupplier.setDataProvider(StartsWithIgnoreCaseItemFilter.New(this.cmbSupplier::getItemLabelGenerator),
			DataProvider.ofCollection(SupplierDAO.INSTANCE.findAll()));
		this.cmbSupplier.setItemLabelGenerator(ItemLabelGeneratorFactory.NonNull(CaptionUtils::resolveCaption));
		this.lblDiscontinued.setText("Discontinued");
		this.chkDiscontinued.setTabIndex(4);
		this.lblUnitprice.setText("Unitprice");
		this.bigdUnitprice.setTabIndex(5);
		this.lblUnitsinstock.setText("Unitsinstock");
		this.nrUnitsinstock.setTabIndex(6);
		this.lblQuantityperunit.setText("Quantityperunit");
		this.txtQuantityperunit.setTabIndex(7);
		this.lblUnitsonorder.setText("Unitsonorder");
		this.nrUnitsonorder.setTabIndex(8);
		this.btnCancel.setText("Cancel");
		this.btnOK.setText("Save");
		this.btnOK.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
		this.btnOK.setIcon(IronIcons.SAVE.create());

		this.binder.forField(this.txtProductname).asRequired().withNullRepresentation("").bind(Product::getProductname,
			Product::setProductname);
		this.binder.forField(this.cmbCategory).asRequired().bind(Product::getCategory, Product::setCategory);
		this.binder.forField(this.cmbSupplier).asRequired().bind(Product::getSupplier, Product::setSupplier);
		this.binder.forField(this.bigdUnitprice).asRequired().bind(Product::getUnitprice, Product::setUnitprice);
		this.binder.forField(this.nrUnitsinstock).asRequired().withConverter(ConverterBuilder.DoubleToShort().build())
			.bind(Product::getUnitsinstock, Product::setUnitsinstock);
		this.binder.forField(this.txtQuantityperunit).asRequired().withNullRepresentation("")
			.bind(Product::getQuantityperunit, Product::setQuantityperunit);
		this.binder.forField(this.nrUnitsonorder).asRequired().withConverter(ConverterBuilder.DoubleToShort().build())
			.bind(Product::getUnitsonorder, Product::setUnitsonorder);
		this.binder.forField(this.chkDiscontinued).bind(Product::isDiscontinued, Product::setDiscontinued);

		this.lblProductname.setSizeUndefined();
		this.lblProductname.getElement().setAttribute("slot", "label");
		this.txtProductname.setWidthFull();
		this.txtProductname.setHeight(null);
		this.formItem.add(this.lblProductname, this.txtProductname);
		this.lblCategory.setSizeUndefined();
		this.lblCategory.getElement().setAttribute("slot", "label");
		this.cmbCategory.setWidthFull();
		this.cmbCategory.setHeight(null);
		this.formItem2.add(this.lblCategory, this.cmbCategory);
		this.lblSupplier.setSizeUndefined();
		this.lblSupplier.getElement().setAttribute("slot", "label");
		this.cmbSupplier.setWidthFull();
		this.cmbSupplier.setHeight(null);
		this.formItem3.add(this.lblSupplier, this.cmbSupplier);
		this.lblDiscontinued.setSizeUndefined();
		this.lblDiscontinued.getElement().setAttribute("slot", "label");
		this.chkDiscontinued.setWidthFull();
		this.chkDiscontinued.setHeight(null);
		this.formItem4.add(this.lblDiscontinued, this.chkDiscontinued);
		this.lblUnitprice.setSizeUndefined();
		this.lblUnitprice.getElement().setAttribute("slot", "label");
		this.bigdUnitprice.setWidthFull();
		this.bigdUnitprice.setHeight(null);
		this.formItem5.add(this.lblUnitprice, this.bigdUnitprice);
		this.lblUnitsinstock.setSizeUndefined();
		this.lblUnitsinstock.getElement().setAttribute("slot", "label");
		this.nrUnitsinstock.setWidthFull();
		this.nrUnitsinstock.setHeight(null);
		this.formItem6.add(this.lblUnitsinstock, this.nrUnitsinstock);
		this.lblQuantityperunit.setSizeUndefined();
		this.lblQuantityperunit.getElement().setAttribute("slot", "label");
		this.txtQuantityperunit.setWidthFull();
		this.txtQuantityperunit.setHeight(null);
		this.formItem7.add(this.lblQuantityperunit, this.txtQuantityperunit);
		this.lblUnitsonorder.setSizeUndefined();
		this.lblUnitsonorder.getElement().setAttribute("slot", "label");
		this.nrUnitsonorder.setWidthFull();
		this.nrUnitsonorder.setHeight(null);
		this.formItem8.add(this.lblUnitsonorder, this.nrUnitsonorder);
		this.form.add(this.formItem, this.formItem2, this.formItem3, this.formItem4, this.formItem5, this.formItem6,
			this.formItem7, this.formItem8);
		this.btnCancel.setWidthFull();
		this.btnCancel.setHeight(null);
		this.btnOK.setWidthFull();
		this.btnOK.setHeight(null);
		this.horizontalLayout.add(this.btnCancel, this.btnOK);
		this.form.setSizeFull();
		this.horizontalLayout.setWidthFull();
		this.horizontalLayout.setHeight(null);
		this.add(this.form, this.horizontalLayout);
		this.setSizeFull();

		this.btnCancel.addClickListener(this::btnCancel_onClick);
		this.btnOK.addClickListener(this::btnOK_onClick);
	} // </generated-code>

	// <generated-code name="variables">
	private FormLayout         form;
	private Checkbox           chkDiscontinued;
	private ComboBox<Supplier> cmbSupplier;
	private Button             btnCancel, btnOK;
	private BigDecimalField    bigdUnitprice;
	private NumberField        nrUnitsinstock, nrUnitsonorder;
	private Binder<Product>    binder;
	private HorizontalLayout   horizontalLayout;
	private Label              lblProductname, lblCategory, lblSupplier, lblDiscontinued, lblUnitprice, lblUnitsinstock,
		lblQuantityperunit, lblUnitsonorder;
	private ComboBox<Category> cmbCategory;
	private TextField          txtProductname, txtQuantityperunit;
	private FormItem           formItem, formItem2, formItem3, formItem4, formItem5, formItem6, formItem7, formItem8;
	// </generated-code>

}
